# Generated by Django 4.0.4 on 2022-10-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('points', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Education', 'Education'), ('Work', 'Work'), ('Fitness', 'Fitness'), ('Social', 'Social'), ('Hobby', 'Hobby')], default=tasks.models.TaskTypes['EDUCATION'], max_length=20)),
                ('image', models.ImageField(default='images/indeks.png', upload_to='images/')),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Occurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progres', models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('finished', 'finished')], default=tasks.models.ProgressType['NOT_STARTED'], max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
